---
# playbook made by Arnaud Crampet 
#- name: "clear SSH keys"
#  command: "echo # > /etc/ssh/ssh_known_hosts"

#- name: "Get SSH keys"
#  command: "ssh-keyscan -H ${servers} >> /etc/ssh/ssh_known_hosts"
#  with_items: "{{ groups['all'] }}"


- include: FS_HOME.yml
  become: true
  tags:
      - fs_tasks
      - always

- include: FS_VAR.yml
  become: true
  tags:
      - fs_tasks
      - always

- include: FS_LOG.yml
  become: true
  tags:
      - fs_tasks
      - always

- include: FS_CLEAN.yml
  become: true
  tags:
      - fs_tasks
      - always

- include: reboot.yml
  become: true
  tags:
      - fs_tasks
      - always