

 - name: Reboot the server
   tags: reboot
   shell: "sleep 5 && reboot"
   async: 1
   poll: 0
    
 - name: Wait for the reboot and reconnect 
   wait_for_connection:
        delay: 60
        timeout: 300

 - name: Check the Uptime of the servers
   shell: "uptime"
   register: Uptime

 - debug: var=Uptime